In [1]:
#this is an example using econml for DML

In [1]:
import econml

from econml.dml import DMLCateEstimator, LinearDMLCateEstimator,SparseLinearDMLCateEstimator
from econml.drlearner import DRLearner 


import numpy as np
from itertools import product
from sklearn.linear_model import Lasso, LassoCV, LogisticRegression, LogisticRegressionCV,LinearRegression
from sklearn.ensemble import RandomForestRegressor,RandomForestClassifier,AdaBoostClassifier,GradientBoostingClassifier,GradientBoostingRegressor,AdaBoostRegressor
from sklearn.dummy import DummyRegressor, DummyClassifier
from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import PolynomialFeatures
import matplotlib.pyplot as plt
import matplotlib
from sklearn.model_selection import train_test_split

%matplotlib inline

#import empirical_calibration as ec
from matplotlib import pyplot as plt
import pandas as pd
import seaborn as sns
sns.set_style('whitegrid')
%config InlineBackend.figure_format='retina'

In [3]:
df = pd.read_csv("lalonde_data_expand.csv")


In [4]:
df.head()


treat  age  education  black  hispanic  married  nodegree        re74  \
0      0   45         11      0         0        1         1  21516.6700   
1      0   21         14      0         0        0         0   3175.9709   
2      0   38         12      0         0        1         0  23039.0200   
3      0   48          6      0         0        1         1  24994.3690   
4      0   18          8      0         0        1         1   1669.2950   

         re75        re78  ...    re74_re74    re74_re75    re75_age  \
0  25243.5510  25564.6700  ...  462967072.0  543157120.0  1135959.80   
1   5852.5649  13496.0800  ...   10086791.0   18587576.0   122903.87   
2  25130.7600  25564.6700  ...  530796416.0  578988096.0   954968.88   
3  25243.5510  25564.6700  ...  624718464.0  630946624.0  1211690.50   
4  10727.6100   9860.8691  ...    2786546.0   17907546.0   193096.98   

   re75_education  re75_black  re75_hispanic  re75_married  re75_nodegree  \
0      277679.060         0.0            0.0     25243.551      25243.551   
1       81935.906         0.0            0.0         0.000          0.000   
2      301569.130         0.0            0.0     25130.760          0.000   
3      151461.310         0.0            0.0     25243.551      25243.551   
4       85820.883         0.0            0.0     10727.610      10727.610   

     re75_re74    re75_re75  
0  543157120.0  637236864.0  
1   18587576.0   34252516.0  
2  578988096.0  631555072.0  
3  630946624.0  637236864.0  
4   17907546.0  115081624.0  

[5 rows x 72 columns]

In [4]:
Y = df['re78']
T = df['treat']
W = df.iloc[:,[1,2,3,4,5,6,7,8]]
X = df.iloc[:,[5]]

In [5]:
X.shape

(16177, 1)

In [6]:
W.head()

age  education  black  hispanic  married  nodegree        re74        re75
0   45         11      0         0        1         1  21516.6700  25243.5510
1   21         14      0         0        0         0   3175.9709   5852.5649
2   38         12      0         0        1         0  23039.0200  25130.7600
3   48          6      0         0        1         1  24994.3690  25243.5510
4   18          8      0         0        1         1   1669.2950  10727.6100

In [7]:
from econml.dml import LinearDMLCateEstimator
from sklearn.linear_model import LogisticRegressionCV
est = LinearDMLCateEstimator(model_t=GradientBoostingClassifier(n_estimators=100), 
                             model_y=GradientBoostingRegressor(n_estimators=100),
                             discrete_treatment=True, random_state=20201002, n_splits = 5)
est.fit(Y, T,None,W,  inference='statsmodels')
est.summary(decimals=10)

Coefficient Results:  X is None, please call intercept_inference to learn the constant!


<class 'econml.utilities.Summary'>
"""
                                        Intercept Results                                        
=================================================================================================
          point_estimate     stderr        zstat        pvalue        ci_lower        ci_upper   
-------------------------------------------------------------------------------------------------
intercept 800.8708485813 635.6548709995 1.2599145938 0.2077001735 -244.6883714715 1846.4300686342
-------------------------------------------------------------------------------------------------
"""

In [41]:
from econml.dml import LinearDMLCateEstimator
from sklearn.linear_model import LogisticRegressionCV
est = DMLCateEstimator(model_t=GradientBoostingClassifier(n_estimators=100), 
                             model_y=GradientBoostingRegressor(n_estimators=100), model_final = LinearRegression()
                             ,discrete_treatment=True, random_state=20201002)
est.fit(Y, T,None,W)


/Users/xiozh/anaconda3/lib/python3.7/site-packages/econml/dml.py:163: UserWarning: The final model has a nonzero intercept for at least one outcome; it will be subtracted, but consider fitting a model without an intercept if possible.
  UserWarning)


In [42]:
est.effect(None, T0=0, T1=1)

array([781.95226628])

In [11]:

est.const_marginal_effect(X)


array([[1148.41497835],
       [ 649.05810012],
       [1148.41497835],
       ...,
       [1148.41497835],
       [1148.41497835],
       [1148.41497835]])

In [12]:
est.const_marginal_effect(X).shape


(16177, 1)

In [13]:
from econml.dml import LinearDMLCateEstimator
from sklearn.linear_model import LogisticRegressionCV
est = LinearDMLCateEstimator(model_t=GradientBoostingClassifier(n_estimators=100), model_y=GradientBoostingRegressor(n_estimators=100),discrete_treatment=True, random_state =20201002)
est.fit(Y, T, None,W,  inference='statsmodels')
est.summary(decimals=10)

Coefficient Results:  X is None, please call intercept_inference to learn the constant!


<class 'econml.utilities.Summary'>
"""
                                       Intercept Results                                        
================================================================================================
          point_estimate     stderr       zstat        pvalue        ci_lower        ci_upper   
------------------------------------------------------------------------------------------------
intercept 781.6365840393 641.966817089 1.2175653994 0.2233891698 -274.3048634321 1837.5780315106
------------------------------------------------------------------------------------------------
"""

In [14]:
# simulation example. 

In [8]:
df = pd.read_csv("simulation.csv")


In [9]:
df.head()

x1         x2         x3         x4         x5        x6         x7  \
0 -0.968214  10.449774   6.699888 -12.999743  -1.578476  9.600975   3.259011   
1 -1.655520  -7.906361   3.674862   4.268746  10.597282  5.996083  -0.261753   
2  0.367583  24.977398  -9.260925 -16.917364   3.740397 -5.121129  -5.817641   
3 -1.180999   0.859065  25.029938   0.236197  13.324658  7.696211 -19.301029   
4  1.515738  -1.609899   3.413305  -8.047482  23.242582 -1.181857  13.162636   

         x8         x9        x10  x11  x12  x13  x14  treat          y1  \
0  4.302259   3.260433  -9.517027    0    0    0    0      0   29.150280   
1  0.513710 -10.802409 -18.845600    1    0    1    1      0 -145.806030   
2  9.510558  -7.282703   1.302011    1    0    1    0      1  -30.317884   
3  6.256372  -0.449694   0.615570    0    0    1    0      1  139.424510   
4  4.899009  -4.769856 -10.075878    0    1    1    0      0   98.110741   

          y2          y3  
0   29.15028   29.150280  
1 -264.40143 -159.806030  
2  344.34308  -30.317884  
3  139.42451  139.424510  
4  152.72362   98.110741

In [10]:
Y1 = df['y1']
Y2 = df['y2']
Y3 = df['y3']
T = df['treat']
W = df.iloc[:,[1,2,3,4,5,6,7,8,9,10,11,12,13]]
X = df.iloc[:,[13]]

In [11]:
W.head()

x2         x3         x4         x5        x6         x7        x8  \
0  10.449774   6.699888 -12.999743  -1.578476  9.600975   3.259011  4.302259   
1  -7.906361   3.674862   4.268746  10.597282  5.996083  -0.261753  0.513710   
2  24.977398  -9.260925 -16.917364   3.740397 -5.121129  -5.817641  9.510558   
3   0.859065  25.029938   0.236197  13.324658  7.696211 -19.301029  6.256372   
4  -1.609899   3.413305  -8.047482  23.242582 -1.181857  13.162636  4.899009   

          x9        x10  x11  x12  x13  x14  
0   3.260433  -9.517027    0    0    0    0  
1 -10.802409 -18.845600    1    0    1    1  
2  -7.282703   1.302011    1    0    1    0  
3  -0.449694   0.615570    0    0    1    0  
4  -4.769856 -10.075878    0    1    1    0

In [12]:
X.head()

x14
0    0
1    1
2    0
3    0
4    0

In [13]:
from econml.dml import LinearDMLCateEstimator
from sklearn.linear_model import LogisticRegressionCV
est = LinearDMLCateEstimator(model_t=GradientBoostingClassifier(n_estimators=100), 
                             model_y=GradientBoostingRegressor(n_estimators=100),
                             discrete_treatment=True, random_state =20201002)
est.fit(Y3, T, None,W,  inference='statsmodels')
est.summary(decimals=10)

Coefficient Results:  X is None, please call intercept_inference to learn the constant!


<class 'econml.utilities.Summary'>
"""
                                  Intercept Results                                  
=====================================================================================
          point_estimate    stderr       zstat     pvalue    ci_lower      ci_upper  
-------------------------------------------------------------------------------------
intercept  27.4463876541 0.9441895553 29.068726188    0.0 25.8933340394 28.9994412687
-------------------------------------------------------------------------------------
"""

In [14]:
from econml.dml import LinearDMLCateEstimator
from sklearn.linear_model import LogisticRegressionCV
est = LinearDMLCateEstimator(model_t=GradientBoostingClassifier(n_estimators=100), 
                             model_y=GradientBoostingRegressor(n_estimators=100),
                             discrete_treatment=True, random_state =20201002)
est.fit(Y3, T, X,W,  inference='statsmodels')
est.summary(decimals=10)

<class 'econml.utilities.Summary'>
"""
                              Coefficient Results                              
===============================================================================
   point_estimate    stderr        zstat     pvalue    ci_lower      ci_upper  
-------------------------------------------------------------------------------
X0  18.8467512769 1.8797469392 10.0262172974    0.0 15.7548427061 21.9386598477
                                  Intercept Results                                   
======================================================================================
          point_estimate    stderr        zstat     pvalue    ci_lower      ci_upper  
--------------------------------------------------------------------------------------
intercept  17.9814391775 1.3555391309 13.2651568429    0.0 15.7517757217 20.2111026334
--------------------------------------------------------------------------------------
"""

In [15]:
est.effect(X, T0=0, T1=1)

array([17.98143918, 36.82819045, 17.98143918, ..., 36.82819045,
       36.82819045, 17.98143918])

NameError: name 'X' is not defined

In [5]:
df = pd.read_csv("lalonde_data_expand.csv")

In [6]:
df.head()

treat  age  education  black  hispanic  married  nodegree        re74  \
0      0   45         11      0         0        1         1  21516.6700   
1      0   21         14      0         0        0         0   3175.9709   
2      0   38         12      0         0        1         0  23039.0200   
3      0   48          6      0         0        1         1  24994.3690   
4      0   18          8      0         0        1         1   1669.2950   

         re75        re78  ...    re74_re74    re74_re75    re75_age  \
0  25243.5510  25564.6700  ...  462967072.0  543157120.0  1135959.80   
1   5852.5649  13496.0800  ...   10086791.0   18587576.0   122903.87   
2  25130.7600  25564.6700  ...  530796416.0  578988096.0   954968.88   
3  25243.5510  25564.6700  ...  624718464.0  630946624.0  1211690.50   
4  10727.6100   9860.8691  ...    2786546.0   17907546.0   193096.98   

   re75_education  re75_black  re75_hispanic  re75_married  re75_nodegree  \
0      277679.060         0.0            0.0     25243.551      25243.551   
1       81935.906         0.0            0.0         0.000          0.000   
2      301569.130         0.0            0.0     25130.760          0.000   
3      151461.310         0.0            0.0     25243.551      25243.551   
4       85820.883         0.0            0.0     10727.610      10727.610   

     re75_re74    re75_re75  
0  543157120.0  637236864.0  
1   18587576.0   34252516.0  
2  578988096.0  631555072.0  
3  630946624.0  637236864.0  
4   17907546.0  115081624.0  

[5 rows x 72 columns]

In [27]:
Y = df['re78']
T = df['treat']
W = df.iloc[:,1:71]

In [29]:
W = df.iloc[:,1:72]

In [31]:
del W['re78']

In [32]:
W

age  education  black  hispanic  married  nodegree        re74  \
0       45         11      0         0        1         1  21516.6700   
1       21         14      0         0        0         0   3175.9709   
2       38         12      0         0        1         0  23039.0200   
3       48          6      0         0        1         1  24994.3690   
4       18          8      0         0        1         1   1669.2950   
...    ...        ...    ...       ...      ...       ...         ...   
16172   33         12      1         0        1         0  20279.9490   
16173   25         14      1         0        1         0  35040.0700   
16174   35          9      1         0        1         1  13602.4300   
16175   35          8      1         0        1         1  13732.0700   
16176   33         11      1         0        1         1  14660.7100   

             re75  age_age  age_education  ...     re74_re74    re74_re75  \
0      25243.5510     2025            495  ...  4.629671e+08  543157120.0   
1       5852.5649      441            294  ...  1.008679e+07   18587576.0   
2      25130.7600     1444            456  ...  5.307964e+08  578988096.0   
3      25243.5510     2304            288  ...  6.247185e+08  630946624.0   
4      10727.6100      324            144  ...  2.786546e+06   17907546.0   
...           ...      ...            ...  ...           ...          ...   
16172  10941.3500     1089            396  ...  4.112764e+08  221890016.0   
16173  11536.5700      625            350  ...  1.227806e+09  404242240.0   
16174  13830.6400     1225            315  ...  1.850261e+08  188130304.0   
16175  17976.1500     1225            280  ...  1.885698e+08  246849760.0   
16176  25142.2400     1089            363  ...  2.149364e+08  368603104.0   

         re75_age  re75_education  re75_black  re75_hispanic  re75_married  \
0      1135959.80      277679.060        0.00            0.0     25243.551   
1       122903.87       81935.906        0.00            0.0         0.000   
2       954968.88      301569.130        0.00            0.0     25130.760   
3      1211690.50      151461.310        0.00            0.0     25243.551   
4       193096.98       85820.883        0.00            0.0     10727.610   
...           ...             ...         ...            ...           ...   
16172   361064.53      131296.190    10941.35            0.0     10941.350   
16173   288414.25      161511.980    11536.57            0.0     11536.570   
16174   484072.38      124475.760    13830.64            0.0     13830.640   
16175   629165.25      143809.200    17976.15            0.0     17976.150   
16176   829693.94      276564.660    25142.24            0.0     25142.240   

       re75_nodegree    re75_re74    re75_re75  
0          25243.551  543157120.0  637236864.0  
1              0.000   18587576.0   34252516.0  
2              0.000  578988096.0  631555072.0  
3          25243.551  630946624.0  637236864.0  
4          10727.610   17907546.0  115081624.0  
...              ...          ...          ...  
16172          0.000  221890016.0  119713128.0  
16173          0.000  404242240.0  133092456.0  
16174      13830.640  188130304.0  191286592.0  
16175      17976.150  246849760.0  323141984.0  
16176      25142.240  368603104.0  632132224.0  

[16177 rows x 70 columns]

In [33]:
from econml.dml import LinearDMLCateEstimator
from sklearn.linear_model import LogisticRegressionCV
est = LinearDMLCateEstimator(model_t=GradientBoostingClassifier(n_estimators=100), 
                             model_y=GradientBoostingRegressor(n_estimators=100),
                             discrete_treatment=True, random_state=20201002, n_splits = 5)
est.fit(Y, T,None,W,  inference='statsmodels')
est.summary(decimals=10)

Coefficient Results:  X is None, please call intercept_inference to learn the constant!


<class 'econml.utilities.Summary'>
"""
                                        Intercept Results                                        
=================================================================================================
          point_estimate     stderr        zstat        pvalue        ci_lower        ci_upper   
-------------------------------------------------------------------------------------------------
intercept 758.3396247951 609.4921193265 1.2442156359 0.2134202106 -244.1856982774 1760.8649478677
-------------------------------------------------------------------------------------------------
"""

In [35]:
x = np.arange(9.).reshape(3, 3)
np.where( x > 5 )

(array([2, 2, 2]), array([0, 1, 2]))

In [36]:
x


array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [37]:
y=np.where( x > 5 )

In [38]:
y

(array([2, 2, 2]), array([0, 1, 2]))

In [40]:

from sklearn.preprocessing import OneHotEncoder

In [42]:
enc = OneHotEncoder(handle_unknown='ignore')
X = [['Male', 1], ['Female', 3], ['Female', 2]]
enc.fit(X)



OneHotEncoder(categorical_features=None, categories=None, drop=None,
              dtype=<class 'numpy.float64'>, handle_unknown='ignore',
              n_values=None, sparse=True)

In [47]:
X

[['Male', 1], ['Female', 3], ['Female', 2]]

In [48]:
enc.categories_
enc.transform([['Female', 1], ['Male', 4]]).toarray()


array([[1., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [45]:
enc.transform([['Female', 1], ['Male', 4]]).toarray()


enc.inverse_transform([[0, 1, 1, 0, 0], [0, 0, 0, 1, 0]])


enc.get_feature_names(['gender', 'group'])

In [46]:
y

OneHotEncoder(categorical_features=None, categories=None, drop=None,
              dtype=<class 'numpy.float64'>, handle_unknown='ignore',
              n_values=None, sparse=True)